#!/usr/bin/env python

import xlrd
import csv

from sys import argv

def convert(filename):
    file = xlrd.open_workbook(filename)
    sheet = file.sheet_by_index(0)
    for rownum in xrange(sheet.nrows):
        print "\t".join(map(str,sheet.row_values(rownum)))

if __name__ == '__main__':
   convert(argv[1])
